var annotated =
[
    [ "admin", "classadmin.html", "classadmin" ],
    [ "Coder", "classCoder.html", "classCoder" ],
    [ "Controller", "classController.html", "classController" ],
    [ "Core", "classCore.html", "classCore" ],
    [ "DB", "classDB.html", "classDB" ],
    [ "Error", "classError.html", "classError" ],
    [ "home", "classhome.html", "classhome" ],
    [ "Install", "classInstall.html", "classInstall" ],
    [ "KAutoloader", "classKAutoloader.html", "classKAutoloader" ],
    [ "mAdmin", "classmAdmin.html", "classmAdmin" ],
    [ "mError", "classmError.html", null ],
    [ "mHome", "classmHome.html", "classmHome" ],
    [ "mInstall", "classmInstall.html", "classmInstall" ],
    [ "Model", "classModel.html", "classModel" ],
    [ "mProfile", "classmProfile.html", "classmProfile" ],
    [ "mReg", "classmReg.html", "classmReg" ],
    [ "profile", "classprofile.html", "classprofile" ],
    [ "Reg", "classReg.html", "classReg" ],
    [ "Registry", "classRegistry.html", "classRegistry" ],
    [ "Request", "classRequest.html", "classRequest" ],
    [ "Session", "classSession.html", "classSession" ],
    [ "SQLParser", "classSQLParser.html", "classSQLParser" ],
    [ "Template", "classTemplate.html", "classTemplate" ],
    [ "vAdmin", "classvAdmin.html", "classvAdmin" ],
    [ "vCreate", "classvCreate.html", "classvCreate" ],
    [ "vError", "classvError.html", "classvError" ],
    [ "vHome", "classvHome.html", "classvHome" ],
    [ "View", "classView.html", "classView" ],
    [ "vInstall", "classvInstall.html", "classvInstall" ],
    [ "vProfile", "classvProfile.html", "classvProfile" ],
    [ "vReg", "classvReg.html", "classvReg" ]
];